# Generated by Django 5.1.1 on 2024-12-31 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=datetime.datetime(2024, 12, 31, 23, 5, 37, 890772, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
