# Generated by Django 5.1.1 on 2024-12-31 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0002_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='POST.poster')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POST.post')),
            ],
        ),
    ]
